### ISSUE TITLE
Fix Jump

### ISSUE THREAD

**Issue by JacobJFM** [Amoriem-Labs/planet-112#11]
Right now if you hold down jump, the player will repeatedly jump just fine, except that they start every jump after the first from some height above the ground. My guess is that the raycast involved in groundcheck just needs a much smaller float as an argument.

**Comment by aderhall** [comment]
Yeah if you turn on debug draw ray you can see it's too long.

I would also recommend moving player and plants off of ignoreRaycast, and put the ground objects on their own layer, with isGrounded only raycasting on the "ground" layer (if possible). It would be kind of annoying to have to keep moving everything to ignoreRaycast, and we might want to do other raycasts between player and non-ground objects in the future.

**Comment by aderhall** [comment]
Thanks @JacobJFM @jaidensayshi
